/**
 * mockDraftPool.js
 * ~200 player pool for the Orange mock draft simulator.
 * Sorted by ADP. ADP values are approximate 2025 consensus.
 */

export const MOCK_DRAFT_POOL = [
  // ─── QBs ──────────────────────────────────────────────────────────────────
  { id: 'q1',  name: 'Lamar Jackson',       position: 'QB', team: 'BAL', adp: 1.8,   projectedPts: 32.4, bye: 14 },
  { id: 'q2',  name: 'Josh Allen',           position: 'QB', team: 'BUF', adp: 3.2,   projectedPts: 31.2, bye: 12 },
  { id: 'q3',  name: 'Jalen Hurts',          position: 'QB', team: 'PHI', adp: 4.1,   projectedPts: 29.8, bye: 5  },
  { id: 'q4',  name: 'Patrick Mahomes',      position: 'QB', team: 'KC',  adp: 7.6,   projectedPts: 27.4, bye: 10 },
  { id: 'q5',  name: 'C.J. Stroud',          position: 'QB', team: 'HOU', adp: 9.4,   projectedPts: 25.6, bye: 14 },
  { id: 'q6',  name: 'Dak Prescott',         position: 'QB', team: 'DAL', adp: 10.2,  projectedPts: 24.6, bye: 7  },
  { id: 'q7',  name: 'Joe Burrow',           position: 'QB', team: 'CIN', adp: 11.8,  projectedPts: 24.1, bye: 9  },
  { id: 'q8',  name: 'Anthony Richardson',   position: 'QB', team: 'IND', adp: 13.4,  projectedPts: 22.8, bye: 14 },
  { id: 'q9',  name: 'Jordan Love',          position: 'QB', team: 'GB',  adp: 15.2,  projectedPts: 22.2, bye: 10 },
  { id: 'q10', name: 'Justin Herbert',       position: 'QB', team: 'LAC', adp: 17.6,  projectedPts: 21.4, bye: 5  },
  { id: 'q11', name: 'Tua Tagovailoa',       position: 'QB', team: 'MIA', adp: 19.8,  projectedPts: 20.8, bye: 10 },
  { id: 'q12', name: 'Trevor Lawrence',      position: 'QB', team: 'JAX', adp: 21.2,  projectedPts: 20.4, bye: 11 },
  { id: 'q13', name: 'Brock Purdy',          position: 'QB', team: 'SF',  adp: 22.6,  projectedPts: 19.8, bye: 9  },
  { id: 'q14', name: 'Sam Darnold',          position: 'QB', team: 'MIN', adp: 25.4,  projectedPts: 18.6, bye: 6  },
  { id: 'q15', name: 'Caleb Williams',       position: 'QB', team: 'CHI', adp: 26.8,  projectedPts: 18.2, bye: 7  },
  { id: 'q16', name: 'Matthew Stafford',     position: 'QB', team: 'LAR', adp: 29.2,  projectedPts: 17.4, bye: 6  },
  { id: 'q17', name: 'Jayden Daniels',       position: 'QB', team: 'WAS', adp: 31.4,  projectedPts: 16.8, bye: 14 },
  { id: 'q18', name: 'Kirk Cousins',         position: 'QB', team: 'ATL', adp: 34.2,  projectedPts: 15.6, bye: 12 },
  { id: 'q19', name: 'Drake Maye',           position: 'QB', team: 'NE',  adp: 36.6,  projectedPts: 14.8, bye: 14 },
  { id: 'q20', name: 'Bo Nix',              position: 'QB', team: 'DEN', adp: 38.4,  projectedPts: 14.2, bye: 14 },

  // ─── RBs ──────────────────────────────────────────────────────────────────
  { id: 'r1',  name: 'Christian McCaffrey',  position: 'RB', team: 'SF',  adp: 2.1,   projectedPts: 28.6, bye: 9  },
  { id: 'r2',  name: 'Saquon Barkley',       position: 'RB', team: 'PHI', adp: 5.4,   projectedPts: 24.2, bye: 5  },
  { id: 'r3',  name: 'Derrick Henry',        position: 'RB', team: 'BAL', adp: 6.2,   projectedPts: 23.1, bye: 14 },
  { id: 'r4',  name: 'Breece Hall',          position: 'RB', team: 'NYJ', adp: 7.8,   projectedPts: 22.4, bye: 12 },
  { id: 'r5',  name: "De'Von Achane",        position: 'RB', team: 'MIA', adp: 8.4,   projectedPts: 21.8, bye: 10 },
  { id: 'r6',  name: 'Bijan Robinson',       position: 'RB', team: 'ATL', adp: 10.4,  projectedPts: 20.6, bye: 12 },
  { id: 'r7',  name: 'Tony Pollard',         position: 'RB', team: 'TEN', adp: 11.2,  projectedPts: 19.6, bye: 5  },
  { id: 'r8',  name: 'Travis Etienne',       position: 'RB', team: 'JAX', adp: 12.6,  projectedPts: 18.4, bye: 11 },
  { id: 'r9',  name: 'Josh Jacobs',          position: 'RB', team: 'GB',  adp: 13.4,  projectedPts: 17.9, bye: 10 },
  { id: 'r10', name: 'Jonathan Taylor',      position: 'RB', team: 'IND', adp: 14.8,  projectedPts: 17.4, bye: 14 },
  { id: 'r11', name: 'Isiah Pacheco',        position: 'RB', team: 'KC',  adp: 16.4,  projectedPts: 16.8, bye: 10 },
  { id: 'r12', name: 'Rachaad White',        position: 'RB', team: 'TB',  adp: 17.8,  projectedPts: 16.2, bye: 11 },
  { id: 'r13', name: 'Aaron Jones',          position: 'RB', team: 'MIN', adp: 18.2,  projectedPts: 15.8, bye: 6  },
  { id: 'r14', name: 'Rhamondre Stevenson',  position: 'RB', team: 'NE',  adp: 19.6,  projectedPts: 15.2, bye: 14 },
  { id: 'r15', name: 'Kyren Williams',       position: 'RB', team: 'LAR', adp: 20.4,  projectedPts: 14.8, bye: 6  },
  { id: 'r16', name: 'D\'Andre Swift',       position: 'RB', team: 'CHI', adp: 21.2,  projectedPts: 14.4, bye: 7  },
  { id: 'r17', name: 'Joe Mixon',            position: 'RB', team: 'HOU', adp: 22.8,  projectedPts: 13.8, bye: 14 },
  { id: 'r18', name: 'James Conner',         position: 'RB', team: 'ARI', adp: 24.6,  projectedPts: 13.2, bye: 11 },
  { id: 'r19', name: 'Jaylen Warren',        position: 'RB', team: 'PIT', adp: 25.4,  projectedPts: 12.8, bye: 9  },
  { id: 'r20', name: 'Tyjae Spears',         position: 'RB', team: 'TEN', adp: 26.2,  projectedPts: 12.4, bye: 5  },
  { id: 'r21', name: 'Gus Edwards',          position: 'RB', team: 'LAC', adp: 27.8,  projectedPts: 11.8, bye: 5  },
  { id: 'r22', name: 'Brian Robinson Jr.',   position: 'RB', team: 'WAS', adp: 29.4,  projectedPts: 11.4, bye: 14 },
  { id: 'r23', name: 'Najee Harris',         position: 'RB', team: 'PIT', adp: 31.2,  projectedPts: 10.8, bye: 9  },
  { id: 'r24', name: 'Kareem Hunt',          position: 'RB', team: 'KC',  adp: 32.6,  projectedPts: 10.4, bye: 10 },
  { id: 'r25', name: 'Ezekiel Elliott',      position: 'RB', team: 'DAL', adp: 34.4,  projectedPts: 9.8,  bye: 7  },
  { id: 'r26', name: 'Dameon Pierce',        position: 'RB', team: 'HOU', adp: 36.2,  projectedPts: 9.2,  bye: 14 },
  { id: 'r27', name: 'Miles Sanders',        position: 'RB', team: 'CAR', adp: 38.4,  projectedPts: 8.8,  bye: 11 },
  { id: 'r28', name: 'Kenneth Walker III',   position: 'RB', team: 'SEA', adp: 39.8,  projectedPts: 8.4,  bye: 10 },
  { id: 'r29', name: 'Chase Brown',          position: 'RB', team: 'CIN', adp: 41.2,  projectedPts: 7.9,  bye: 9  },
  { id: 'r30', name: 'Javonte Williams',     position: 'RB', team: 'DEN', adp: 43.4,  projectedPts: 7.4,  bye: 14 },
  { id: 'r31', name: 'Chuba Hubbard',        position: 'RB', team: 'CAR', adp: 45.2,  projectedPts: 7.0,  bye: 11 },
  { id: 'r32', name: 'Clyde Edwards-Helaire',position: 'RB', team: 'KC',  adp: 47.6,  projectedPts: 6.6,  bye: 10 },
  { id: 'r33', name: 'Zack Moss',            position: 'RB', team: 'CIN', adp: 49.2,  projectedPts: 6.2,  bye: 9  },
  { id: 'r34', name: 'Cam Akers',            position: 'RB', team: 'MIN', adp: 51.4,  projectedPts: 5.8,  bye: 6  },
  { id: 'r35', name: 'Tyler Allgeier',       position: 'RB', team: 'ATL', adp: 53.2,  projectedPts: 5.4,  bye: 12 },
  { id: 'r36', name: 'Antonio Gibson',       position: 'RB', team: 'NE',  adp: 55.6,  projectedPts: 5.0,  bye: 14 },

  // ─── WRs ──────────────────────────────────────────────────────────────────
  { id: 'w1',  name: 'CeeDee Lamb',          position: 'WR', team: 'DAL', adp: 2.4,   projectedPts: 26.8, bye: 7  },
  { id: 'w2',  name: "Ja'Marr Chase",        position: 'WR', team: 'CIN', adp: 3.8,   projectedPts: 25.4, bye: 9  },
  { id: 'w3',  name: 'Tyreek Hill',          position: 'WR', team: 'MIA', adp: 4.6,   projectedPts: 23.2, bye: 10 },
  { id: 'w4',  name: 'Amon-Ra St. Brown',    position: 'WR', team: 'DET', adp: 7.2,   projectedPts: 22.1, bye: 11 },
  { id: 'w5',  name: 'Stefon Diggs',         position: 'WR', team: 'HOU', adp: 8.8,   projectedPts: 21.4, bye: 14 },
  { id: 'w6',  name: 'Puka Nacua',           position: 'WR', team: 'LAR', adp: 9.8,   projectedPts: 20.4, bye: 6  },
  { id: 'w7',  name: 'Davante Adams',        position: 'WR', team: 'LV',  adp: 11.4,  projectedPts: 18.2, bye: 8  },
  { id: 'w8',  name: 'DJ Moore',             position: 'WR', team: 'CHI', adp: 12.2,  projectedPts: 17.8, bye: 7  },
  { id: 'w9',  name: 'A.J. Brown',           position: 'WR', team: 'PHI', adp: 13.6,  projectedPts: 17.4, bye: 5  },
  { id: 'w10', name: 'Keenan Allen',         position: 'WR', team: 'CHI', adp: 15.8,  projectedPts: 16.9, bye: 7  },
  { id: 'w11', name: 'Josh Downs',           position: 'WR', team: 'IND', adp: 17.4,  projectedPts: 16.2, bye: 14 },
  { id: 'w12', name: 'Jaylen Waddle',        position: 'WR', team: 'MIA', adp: 18.6,  projectedPts: 15.8, bye: 10 },
  { id: 'w13', name: 'Deebo Samuel',         position: 'WR', team: 'SF',  adp: 19.8,  projectedPts: 15.4, bye: 9  },
  { id: 'w14', name: 'DeVonta Smith',        position: 'WR', team: 'PHI', adp: 21.4,  projectedPts: 14.8, bye: 5  },
  { id: 'w15', name: 'Christian Kirk',       position: 'WR', team: 'JAX', adp: 22.8,  projectedPts: 14.2, bye: 11 },
  { id: 'w16', name: 'Terry McLaurin',       position: 'WR', team: 'WAS', adp: 24.2,  projectedPts: 13.8, bye: 14 },
  { id: 'w17', name: 'Gabe Davis',           position: 'WR', team: 'JAX', adp: 25.6,  projectedPts: 13.4, bye: 11 },
  { id: 'w18', name: 'Chris Olave',          position: 'WR', team: 'NO',  adp: 27.2,  projectedPts: 12.8, bye: 12 },
  { id: 'w19', name: 'Calvin Ridley',        position: 'WR', team: 'TEN', adp: 28.8,  projectedPts: 12.4, bye: 5  },
  { id: 'w20', name: "Drake London",         position: 'WR', team: 'ATL', adp: 30.4,  projectedPts: 12.0, bye: 12 },
  { id: 'w21', name: 'Rashee Rice',          position: 'WR', team: 'KC',  adp: 32.2,  projectedPts: 11.6, bye: 10 },
  { id: 'w22', name: 'Garrett Wilson',       position: 'WR', team: 'NYJ', adp: 33.8,  projectedPts: 11.2, bye: 12 },
  { id: 'w23', name: 'Mike Evans',           position: 'WR', team: 'TB',  adp: 35.4,  projectedPts: 10.8, bye: 11 },
  { id: 'w24', name: 'Quentin Johnston',     position: 'WR', team: 'LAC', adp: 37.2,  projectedPts: 10.4, bye: 5  },
  { id: 'w25', name: "Marvin Harrison Jr.",  position: 'WR', team: 'ARI', adp: 38.8,  projectedPts: 10.0, bye: 11 },
  { id: 'w26', name: 'Elijah Moore',         position: 'WR', team: 'CLE', adp: 40.4,  projectedPts: 9.6,  bye: 5  },
  { id: 'w27', name: 'Brandon Aiyuk',        position: 'WR', team: 'SF',  adp: 42.2,  projectedPts: 9.2,  bye: 9  },
  { id: 'w28', name: 'Darnell Mooney',       position: 'WR', team: 'ATL', adp: 43.8,  projectedPts: 8.8,  bye: 12 },
  { id: 'w29', name: 'Wan\'Dale Robinson',   position: 'WR', team: 'NYG', adp: 45.6,  projectedPts: 8.4,  bye: 13 },
  { id: 'w30', name: 'Romeo Doubs',          position: 'WR', team: 'GB',  adp: 47.4,  projectedPts: 8.0,  bye: 10 },
  { id: 'w31', name: 'Odell Beckham Jr.',    position: 'WR', team: 'MIA', adp: 49.2,  projectedPts: 7.6,  bye: 10 },
  { id: 'w32', name: 'Jordan Addison',       position: 'WR', team: 'MIN', adp: 51.0,  projectedPts: 7.2,  bye: 6  },
  { id: 'w33', name: 'Zay Jones',            position: 'WR', team: 'ARI', adp: 52.8,  projectedPts: 6.8,  bye: 11 },
  { id: 'w34', name: 'Kadarius Toney',       position: 'WR', team: 'KC',  adp: 54.4,  projectedPts: 6.4,  bye: 10 },
  { id: 'w35', name: 'Kendrick Bourne',      position: 'WR', team: 'NE',  adp: 56.2,  projectedPts: 6.0,  bye: 14 },
  { id: 'w36', name: 'Tutu Atwell',          position: 'WR', team: 'LAR', adp: 58.0,  projectedPts: 5.6,  bye: 6  },

  // ─── TEs ──────────────────────────────────────────────────────────────────
  { id: 't1',  name: 'Sam LaPorta',          position: 'TE', team: 'DET', adp: 8.8,   projectedPts: 16.4, bye: 11 },
  { id: 't2',  name: 'Mark Andrews',         position: 'TE', team: 'BAL', adp: 9.2,   projectedPts: 15.8, bye: 14 },
  { id: 't3',  name: 'Trey McBride',         position: 'TE', team: 'ARI', adp: 10.8,  projectedPts: 14.6, bye: 11 },
  { id: 't4',  name: 'Jake Ferguson',        position: 'TE', team: 'DAL', adp: 14.4,  projectedPts: 12.8, bye: 7  },
  { id: 't5',  name: 'Travis Kelce',         position: 'TE', team: 'KC',  adp: 15.6,  projectedPts: 12.2, bye: 10 },
  { id: 't6',  name: 'Jonnu Smith',          position: 'TE', team: 'MIA', adp: 18.6,  projectedPts: 10.4, bye: 10 },
  { id: 't7',  name: 'Cole Kmet',            position: 'TE', team: 'CHI', adp: 20.4,  projectedPts: 9.8,  bye: 7  },
  { id: 't8',  name: 'Kyle Pitts',           position: 'TE', team: 'ATL', adp: 22.2,  projectedPts: 9.4,  bye: 12 },
  { id: 't9',  name: 'Pat Freiermuth',       position: 'TE', team: 'PIT', adp: 24.6,  projectedPts: 8.8,  bye: 9  },
  { id: 't10', name: 'Juwan Johnson',        position: 'TE', team: 'NO',  adp: 27.2,  projectedPts: 8.2,  bye: 12 },
  { id: 't11', name: 'Evan Engram',          position: 'TE', team: 'JAX', adp: 29.4,  projectedPts: 7.6,  bye: 11 },
  { id: 't12', name: 'Tyler Higbee',         position: 'TE', team: 'LAR', adp: 32.2,  projectedPts: 7.0,  bye: 6  },
  { id: 't13', name: 'Isaiah Likely',        position: 'TE', team: 'BAL', adp: 34.4,  projectedPts: 6.4,  bye: 14 },
  { id: 't14', name: 'Tucker Kraft',         position: 'TE', team: 'GB',  adp: 36.8,  projectedPts: 5.8,  bye: 10 },
  { id: 't15', name: 'Dawson Knox',          position: 'TE', team: 'BUF', adp: 39.2,  projectedPts: 5.2,  bye: 12 },
  { id: 't16', name: 'Gerald Everett',       position: 'TE', team: 'LAC', adp: 42.4,  projectedPts: 4.8,  bye: 5  },
  { id: 't17', name: 'Noah Fant',            position: 'TE', team: 'SEA', adp: 45.6,  projectedPts: 4.4,  bye: 10 },
  { id: 't18', name: 'Greg Dulcich',         position: 'TE', team: 'DEN', adp: 48.2,  projectedPts: 4.0,  bye: 14 },

  // ─── Ks ───────────────────────────────────────────────────────────────────
  { id: 'k1',  name: 'Harrison Butker',      position: 'K',  team: 'KC',  adp: 36.2,  projectedPts: 10.8, bye: 10 },
  { id: 'k2',  name: 'Evan McPherson',       position: 'K',  team: 'CIN', adp: 37.4,  projectedPts: 10.4, bye: 9  },
  { id: 'k3',  name: 'Brandon Aubrey',       position: 'K',  team: 'DAL', adp: 38.1,  projectedPts: 10.2, bye: 7  },
  { id: 'k4',  name: 'Jake Elliott',         position: 'K',  team: 'PHI', adp: 39.2,  projectedPts: 9.8,  bye: 5  },
  { id: 'k5',  name: 'Tyler Bass',           position: 'K',  team: 'BUF', adp: 40.6,  projectedPts: 9.4,  bye: 12 },
  { id: 'k6',  name: 'Justin Tucker',        position: 'K',  team: 'BAL', adp: 41.8,  projectedPts: 9.2,  bye: 14 },
  { id: 'k7',  name: 'Younghoe Koo',         position: 'K',  team: 'ATL', adp: 43.2,  projectedPts: 8.8,  bye: 12 },
  { id: 'k8',  name: 'Chris Boswell',        position: 'K',  team: 'PIT', adp: 44.6,  projectedPts: 8.6,  bye: 9  },
  { id: 'k9',  name: 'Greg Zuerlein',        position: 'K',  team: 'NYG', adp: 46.0,  projectedPts: 8.2,  bye: 13 },
  { id: 'k10', name: 'Matt Gay',             position: 'K',  team: 'IND', adp: 47.4,  projectedPts: 7.8,  bye: 14 },
  { id: 'k11', name: 'Wil Lutz',             position: 'K',  team: 'DEN', adp: 48.8,  projectedPts: 7.4,  bye: 14 },
  { id: 'k12', name: 'Cairo Santos',         position: 'K',  team: 'CHI', adp: 50.2,  projectedPts: 7.0,  bye: 7  },

  // ─── DEFs ─────────────────────────────────────────────────────────────────
  { id: 'def1', name: 'San Francisco 49ers', position: 'DEF', team: 'SF',  adp: 34.8, projectedPts: 12.4, bye: 9  },
  { id: 'def2', name: 'Dallas Cowboys',      position: 'DEF', team: 'DAL', adp: 35.2, projectedPts: 11.8, bye: 7  },
  { id: 'def3', name: 'Baltimore Ravens',    position: 'DEF', team: 'BAL', adp: 35.6, projectedPts: 11.6, bye: 14 },
  { id: 'def4', name: 'New York Jets',       position: 'DEF', team: 'NYJ', adp: 36.4, projectedPts: 11.2, bye: 12 },
  { id: 'def5', name: 'Kansas City Chiefs',  position: 'DEF', team: 'KC',  adp: 37.2, projectedPts: 10.8, bye: 10 },
  { id: 'def6', name: 'Pittsburgh Steelers', position: 'DEF', team: 'PIT', adp: 38.0, projectedPts: 10.4, bye: 9  },
  { id: 'def7', name: 'Cleveland Browns',    position: 'DEF', team: 'CLE', adp: 39.2, projectedPts: 10.0, bye: 5  },
  { id: 'def8', name: 'Philadelphia Eagles', position: 'DEF', team: 'PHI', adp: 40.4, projectedPts: 9.6,  bye: 5  },
  { id: 'def9', name: 'Buffalo Bills',       position: 'DEF', team: 'BUF', adp: 41.6, projectedPts: 9.2,  bye: 12 },
  { id: 'def10',name: 'Indianapolis Colts',  position: 'DEF', team: 'IND', adp: 42.8, projectedPts: 8.8,  bye: 14 },
  { id: 'def11',name: 'Miami Dolphins',      position: 'DEF', team: 'MIA', adp: 44.0, projectedPts: 8.4,  bye: 10 },
  { id: 'def12',name: 'New England Patriots',position: 'DEF', team: 'NE',  adp: 45.2, projectedPts: 8.0,  bye: 14 },
];

export const BOT_TEAM_NAMES = [
  'Gridiron Ghosts', 'Blitz Kings', 'End Zone Elite', 'Touchdown Tyrants',
  'Red Zone Rangers', 'Fantasy Sharks', 'Bench Warmers FC', 'Draft Day Demons',
  'Pigskin Pirates', 'The Waiver Wire', 'Turf Monsters', 'Fourth & Forever',
];
