export const DRAFT_POOL = [
  { id: 's1',  name: 'Jahmyr Gibbs',       position: 'RB',  team: 'DET', adp: 1.7,  projectedPts: 27.8, bye: 5  },
  { id: 's2',  name: 'Bijan Robinson',      position: 'RB',  team: 'ATL', adp: 1.9,  projectedPts: 27.6, bye: 11 },
  { id: 's3',  name: 'Puka Nacua',          position: 'WR',  team: 'LAR', adp: 2.9,  projectedPts: 26.1, bye: 6  },
  { id: 's4',  name: "Ja'Marr Chase",       position: 'WR',  team: 'CIN', adp: 3.9,  projectedPts: 25.8, bye: 7  },
  { id: 's5',  name: 'Christian McCaffrey', position: 'RB',  team: 'SF',  adp: 5.6,  projectedPts: 26.8, bye: 9  },
  { id: 's6',  name: 'Jaxon Smith-Njigba',  position: 'WR',  team: 'SEA', adp: 5.8,  projectedPts: 25.2, bye: 5  },
  { id: 's7',  name: 'Amon-Ra St. Brown',   position: 'WR',  team: 'DET', adp: 7.0,  projectedPts: 24.9, bye: 5  },
  { id: 's8',  name: 'Jonathan Taylor',     position: 'RB',  team: 'IND', adp: 7.4,  projectedPts: 26.4, bye: 14 },
  { id: 's9',  name: "De'Von Achane",       position: 'RB',  team: 'MIA', adp: 9.9,  projectedPts: 25.8, bye: 6  },
  { id: 's10', name: 'Drake London',        position: 'WR',  team: 'ATL', adp: 10.2, projectedPts: 24.1, bye: 11 },
  { id: 's11', name: 'CeeDee Lamb',         position: 'WR',  team: 'DAL', adp: 11.3, projectedPts: 23.9, bye: 7  },
  { id: 's12', name: 'Rashee Rice',         position: 'WR',  team: 'KC',  adp: 11.6, projectedPts: 23.7, bye: 11 },
  { id: 's13', name: 'Chase Brown',         position: 'RB',  team: 'CIN', adp: 12.2, projectedPts: 24.1, bye: 7  },
  { id: 's14', name: 'Ashton Jeanty',       position: 'RB',  team: 'LV',  adp: 14.0, projectedPts: 23.6, bye: 8  },
  { id: 's15', name: 'Justin Jefferson',    position: 'WR',  team: 'MIN', adp: 14.2, projectedPts: 23.4, bye: 6  },
  { id: 's16', name: 'Jayden Daniels',      position: 'QB',  team: 'WAS', adp: 14.0, projectedPts: 29.5, bye: 14 },
  { id: 's17', name: 'Drake Maye',          position: 'QB',  team: 'NE',  adp: 15.0, projectedPts: 28.1, bye: 14 },
  { id: 's18', name: 'Brock Bowers',        position: 'TE',  team: 'LV',  adp: 16.0, projectedPts: 18.2, bye: 8  },
  { id: 's19', name: 'Saquon Barkley',      position: 'RB',  team: 'PHI', adp: 17.0, projectedPts: 23.1, bye: 5  },
  { id: 's20', name: 'Garrett Wilson',      position: 'WR',  team: 'NYJ', adp: 18.0, projectedPts: 22.8, bye: 12 },
  { id: 's21', name: 'Sam LaPorta',         position: 'TE',  team: 'DET', adp: 20.0, projectedPts: 17.1, bye: 5  },
  { id: 's22', name: 'Tyreek Hill',         position: 'WR',  team: 'MIA', adp: 21.0, projectedPts: 22.5, bye: 6  },
  { id: 's23', name: 'James Cook',          position: 'RB',  team: 'BUF', adp: 22.0, projectedPts: 22.9, bye: 12 },
  { id: 's24', name: 'Lamar Jackson',       position: 'QB',  team: 'BAL', adp: 23.0, projectedPts: 32.1, bye: 14 },
  { id: 's25', name: 'Derrick Henry',       position: 'RB',  team: 'BAL', adp: 24.0, projectedPts: 22.6, bye: 14 },
  { id: 's26', name: 'DK Metcalf',          position: 'WR',  team: 'PIT', adp: 25.0, projectedPts: 21.9, bye: 9  },
  { id: 's27', name: 'Travis Kelce',        position: 'TE',  team: 'KC',  adp: 26.0, projectedPts: 16.8, bye: 11 },
  { id: 's28', name: 'Josh Allen',          position: 'QB',  team: 'BUF', adp: 29.0, projectedPts: 33.2, bye: 12 },
  { id: 's29', name: 'Breece Hall',         position: 'RB',  team: 'NYJ', adp: 30.0, projectedPts: 21.8, bye: 12 },
  { id: 's30', name: 'Nico Collins',        position: 'WR',  team: 'HOU', adp: 32.0, projectedPts: 20.9, bye: 14 },
  { id: 's31', name: 'Tony Pollard',        position: 'RB',  team: 'TEN', adp: 36.0, projectedPts: 20.4, bye: 6  },
  { id: 's32', name: 'Malik Nabers',        position: 'WR',  team: 'NYG', adp: 38.0, projectedPts: 20.2, bye: 9  },
  { id: 's33', name: 'Patrick Mahomes',     position: 'QB',  team: 'KC',  adp: 40.0, projectedPts: 31.8, bye: 11 },
  { id: 's34', name: 'Tee Higgins',         position: 'WR',  team: 'CIN', adp: 44.0, projectedPts: 19.8, bye: 7  },
  { id: 's35', name: 'David Njoku',         position: 'TE',  team: 'CLE', adp: 46.0, projectedPts: 15.9, bye: 5  },
  { id: 's36', name: 'Brian Thomas Jr',     position: 'WR',  team: 'JAX', adp: 48.0, projectedPts: 19.5, bye: 14 },
  { id: 's37', name: 'Kyler Murray',        position: 'QB',  team: 'ARI', adp: 55.0, projectedPts: 29.8, bye: 11 },
  { id: 's38', name: 'Zay Flowers',         position: 'WR',  team: 'BAL', adp: 57.0, projectedPts: 18.8, bye: 14 },
  { id: 's39', name: 'Dallas Goedert',      position: 'TE',  team: 'PHI', adp: 66.0, projectedPts: 15.2, bye: 5  },
  { id: 's40', name: 'Seattle Seahawks',    position: 'DEF', team: 'SEA', adp: 120.0, projectedPts: 12.0, bye: 5  },
  { id: 's41', name: 'San Francisco 49ers', position: 'DEF', team: 'SF',  adp: 125.0, projectedPts: 11.8, bye: 9  },
  { id: 's42', name: 'Harrison Butker',     position: 'K',   team: 'KC',  adp: 130.0, projectedPts: 11.2, bye: 11 },
  { id: 's43', name: 'Evan McPherson',      position: 'K',   team: 'CIN', adp: 135.0, projectedPts: 11.0, bye: 7  },
];

export const BYE_WEEKS = {
  ARI: 11, ATL: 11, BAL: 14, BUF: 12, CAR: 11, CHI: 7,
  CIN: 7,  CLE: 5,  DAL: 7,  DEN: 14, DET: 5,  GB: 6,
  HOU: 14, IND: 14, JAX: 14, KC: 11,  LAC: 5,  LAR: 6,
  LV: 8,   MIA: 6,  MIN: 6,  NE: 14,  NO: 8,   NYG: 9,
  NYJ: 12, PHI: 5,  PIT: 9,  SEA: 5,  SF: 9,   TB: 11,
  TEN: 6,  WAS: 14,
};

export const PLAYER_DETAILS = {};

export const MY_ROSTER = [];